name: Weekly Report

on:
 workflow_dispatch:

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        env:
          SENDER: ${{ env.SENDER }}
          RECIPIENT: ${{ env.RECIPIENT }}
          X_API_KEY: ${{ env.X_API_KEY }}
          GOOGLE_APP_PWD: ${{ env.GOOGLE_APP_PWD }}
      - run: pip install -r requirements.txt
      - run: python weekly-report.py
